language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install .
  - pip install -r requirements-dev.txt
script: python setup.py test

# setting sudo to "false" allows running on travis-ci new infra (docker)
sudo: false
